services:
  quantm-fe:
    image: quantm-frontend:latest
    container_name: quantm-fe
    restart: unless-stopped
    ports:
      - '4200:80'
    environment:
      - SERVICE_ROLE=frontend
    networks:
      - quantm-shared-network

networks:
  quantm-shared-network:
    external: true
    name: quantm-shared-network
