services:
  quantm-fe-blue:
    image: quantm-frontend:latest
    container_name: quantm-fe-blue
    restart: unless-stopped
    ports:
      - '4200:80'
    networks:
      - quantm-network

  quantm-fe-green:
    image: quantm-frontend:latest
    container_name: quantm-fe-green
    restart: unless-stopped
    ports:
      - '4400:80'
    networks:
      - quantm-network

networks:
  quantm-network:
    name: quantm_network
